### ISSUE TITLE
Archive: Настроить оповещения по email о нехватке свободного места на диске

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/archive.morevnaproject.org#10]
https://gist.github.com/fduran/1870429
https://www.linuxjournal.com/content/tech-tip-send-email-alert-when-your-disk-space-gets-low

**Comment by evgenijkatunov** [comment]
готово

**Comment by morevnaproject** [comment]
Надо проверить работает ли оповещение. Для этого надо временно поставить пороговое значение ниже, чем текущий объём занятого места. И проверить придёт ли мне письмо. ^__^
