### ISSUE TITLE
Ошибки в параметрах

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/archive.morevnaproject.org#14]
Ругается в настройках:
![screenshot_004](https://user-images.githubusercontent.com/332868/74349164-675a2800-4de6-11ea-994e-2585bc488580.png)

Скорее всего нужно volume прописать nextcloud_data в контейнер "cron". ^__^

**Comment by evgenijkatunov** [comment]
Готово, но есть варнинги, надо будет посмотреть на них
