### ISSUE TITLE
Сделать редирект для https://archive.morevnaproject.org/

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/archive.morevnaproject.org#16]
В данныq момент https://archive.morevnaproject.org/ перенаправляет на https://archive.morevnaproject.org/login.

Можно ли сделать так, чтобы https://archive.morevnaproject.org/ перенаправлял на другой URL - https://morevnaproject.org/library/

Наверное, вот так -
https://bjornjohansen.no/nginx-redirect

**Comment by morevnaproject** [comment]
@evgenijkatunov Посмотри, пожалуйста, как будет время. ^__^

**Comment by evgenijkatunov** [comment]
Сделал редирект, но не нравится поведение если кликнуть в лого Nextcloud происхоит редирект, возможно где-то еще есть похожее поведение.
Что бы отключить нужно удалить в `nginx.conf` блок `location = /`

**Comment by morevnaproject** [comment]
Мне всё нравится, спасибо! Логотип NextCloud потом поменяю на логотип Моревны, так что будет всё логично. ^__^
