### ISSUE TITLE
Archive: Установить плагин ShareRenamer для NextCloud

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/archive.morevnaproject.org#7]
https://github.com/DecaTec/sharerenamer

Да, я в курсе про security issue (https://help.nextcloud.com/t/custom-share-links/2729/19), но мы не планируем размещать "секретные" ссылки на этом сервере. ^__^

**Comment by evgenijkatunov** [comment]
Блокирует задачу https://github.com/DecaTec/sharerenamer/issues/21

**Comment by morevnaproject** [comment]
Оооох, да. Будем ждать.

**Comment by morevnaproject** [comment]
@evgenijkatunov Как вариант, можно попробовать расшарить папку без плагина и потом отредактировать базу данных. =D

**Comment by morevnaproject** [comment]
@evgenijkatunov Может временно поднять phpmyadmin ([docker](https://hub.docker.com/r/phpmyadmin/phpmyadmin/)) и через него отредактировать ссылку в базе данных?

**Comment by evgenijkatunov** [comment]
Пока захардкодил токен

**Comment by evgenijkatunov** [comment]
Табличка oc_share для нужного file_target ужно поменять token

**Comment by morevnaproject** [comment]
Спасибо, этого достаточно! ^__^
